#Your Site name.. You can put html in here to use a logo image
sitename: LookGit

#The tag line under your logo
tagline: Your friendly git server

#The copyright info for your git repos
copyright: Copyright &copy; 2008 Your Company